// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voicemail;

#nullable disable

namespace Voicemail.Migrations
{
    [DbContext(typeof(VoicemailContext))]
    [Migration("20250119040710_AddCallCompleted")]
    partial class AddCallCompleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Voicemail.Models.AddressBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.HasIndex("NumberRaw")
                        .IsUnique();

                    b.ToTable("AddressBookEntries");
                });

            modelBuilder.Entity("Voicemail.Models.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<string>("NumberForwardedFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberFromRaw")
                        .HasColumnType("TEXT")
                        .HasColumnName("NumberFrom");

                    b.Property<string>("NumberTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Processed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecordingDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Voicemail.Models.CallerId", b =>
                {
                    b.Property<int>("CallId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallerName")
                        .HasColumnType("TEXT");

                    b.HasKey("CallId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Voicemail.Models.Transcript", b =>
                {
                    b.Property<int>("CallId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MentionedCompanies")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MentionedNumbers")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MentionedPeople")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("TEXT");

                    b.HasKey("CallId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Voicemail.Models.CallerId", b =>
                {
                    b.HasOne("Voicemail.Models.Call", null)
                        .WithOne("CallerId")
                        .HasForeignKey("Voicemail.Models.CallerId", "CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Voicemail.Models.Transcript", b =>
                {
                    b.HasOne("Voicemail.Models.Call", null)
                        .WithOne("Transcript")
                        .HasForeignKey("Voicemail.Models.Transcript", "CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Voicemail.Models.Call", b =>
                {
                    b.Navigation("CallerId");

                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
