// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voicemail;

#nullable disable

namespace Voicemail.Migrations
{
    [DbContext(typeof(VoicemailContext))]
    partial class VoicemailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Voicemail.Models.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberForwardedFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecordingDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Voicemail.Models.Transcript", b =>
                {
                    b.Property<int>("CallId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MentionedCompanies")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MentionedNumbers")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MentionedPeople")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("TEXT");

                    b.HasKey("CallId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Voicemail.Models.Transcript", b =>
                {
                    b.HasOne("Voicemail.Models.Call", null)
                        .WithOne("Transcript")
                        .HasForeignKey("Voicemail.Models.Transcript", "CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Voicemail.Models.Call", b =>
                {
                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
